// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzjQ28kRZl4Wm1ofVyJn43L1OBItOnPfY',
    appId: '1:99150711018:web:bf814ea1a595fc700e2f93',
    messagingSenderId: '99150711018',
    projectId: 'medi-flow-db',
    authDomain: 'medi-flow-db.firebaseapp.com',
    storageBucket: 'medi-flow-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGhJcGi7m5Z8NSZ5LRpK2ng_EXiwQdR4',
    appId: '1:99150711018:android:c0e8e4f1e78995710e2f93',
    messagingSenderId: '99150711018',
    projectId: 'medi-flow-db',
    storageBucket: 'medi-flow-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoVJ-eGW-DGXiY1sexqfKjIvHAbaiRuo',
    appId: '1:99150711018:ios:98f98a73ebf089100e2f93',
    messagingSenderId: '99150711018',
    projectId: 'medi-flow-db',
    storageBucket: 'medi-flow-db.firebasestorage.app',
    iosClientId: '99150711018-sd4irc3m9mu0fo1s3p09ieov4n13q5mq.apps.googleusercontent.com',
    iosBundleId: 'com.mediflow.app.mediFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzjQ28kRZl4Wm1ofVyJn43L1OBItOnPfY',
    appId: '1:99150711018:web:69162898be6980200e2f93',
    messagingSenderId: '99150711018',
    projectId: 'medi-flow-db',
    authDomain: 'medi-flow-db.firebaseapp.com',
    storageBucket: 'medi-flow-db.firebasestorage.app',
  );
}
